# 開始  RMarkdown 在 github.io 的冒險之旅

主要是根據  [Alison Hill 關於 blogdown 的 2021 更新](https://alison.rbind.io/post/new-year-new-blogdown/) *1, (除非有其他的參考文章會特別標出)

## R Markdown 的基本指令 *2

```
## 參考用, 待會兒執行時, 會有詳細指令說明
## 安裝套件 Install packages from CRAN

> if (!requireNamespace("remotes")) install.packages("remotes")  ## install remotes

## install blogdown from CRAN
> install.packages("blogdown") 
## Or, install blogdown from GitHub
> remotes::install_github("rstudio/blogdown")

## blogdown 是基於 Hugo (https://gohugo.io) 靜態網頁產生器, 需要  blogdown 下載並安裝 hugo
> blogdown::install_hugo()

## 安裝後, 如果要開啟 server 的 preview, 就執行以下指令
> blogdown::serve_site()
```

## Create project (Ref 1. Step 2 Create project)
- RStudio 選擇  File > New Project > Version Control > Git
- 複製 github 的 url, 我的例子是 https://github.com/MarconiJiang/marconijiang.github.io.git
- Create Project  

這時候, RStudio 會開個全新的畫面, 下載 marconijiang.github.io 的內容, 同時 file 目錄指向筆電 local repo 的目錄


## Create site (Ref 1. Step 3 Create site)
### 安裝 blogdown

```
## 到 RStudio 的 console 下, 執行以下指令
> if (!requireNamespace("remotes")) install.packages("remotes")
> remotes::install_github("rstudio/blogdown")

##  完成後, 會出現安裝完成字樣
##  * DONE (blogdown)
```

### 在 RStudio / blogdown 下創建新的網站    
執行以下指令

```
> library(blogdown)
> blogdown::new_site(theme = 'yihui/hugo-lithium')
```

原始文章安裝的是另一個主題 (theme), 我嘗試的做了些修改, 都是出現錯誤後, 發現 error message 裡面嘗試去 github 尋找 lithium, 因此我 google 了 "github lithium theme", 找到了至少 3 個 github 包含 lithium 這個主題 (theme), 但是, 只有其中一個的 README.md 說明清楚如何在 blogdown 上安裝, 就照著他的說明進行    

- [Yihui Hugo Lithium ](https://github.com/yihui/hugo-lithium)          ## 清楚說明, 雖然是從 [jrutheiser](https://github.com/jrutheiser/hugo-lithium-theme) fork 出來
- [Jrutheiser Hugo Lithium](https://github.com/jrutheiser/hugo-lithium-theme)    ## 應該是原始出處
- [janikvonrotz Hugo Lithium](https://github.com/janikvonrotz/hugo-lithium-theme)
- [Hugo Lithium 官網](https://themes.gohugo.io/hugo-lithium-theme/)

```
## 以下為錯誤嘗試, 不必重複
> new_site(theme = "wowchemy/starter-academic")   ## 原始文章作法

也參考了 https://bookdown.org/yihui/blogdown/other-themes.html  的說明
> blogdown::new_site(theme = "lxndrblz/anatole")

> new_site(theme = "Lithium")       ##  我的錯誤嘗試
> new_site(theme = "Hugo/Lithium")  ##  我的錯誤嘗試
```  

需要再按 'y' 來確定執行後, RStudio 就開始創建一個新的網站,  有三個方式可以看到網頁內容(雖然目前內容是空的)
1. RStudio 右下方的 Viewer 視窗(在 Files 的右邊)
2. Viewer 視窗下, 有個箭頭的 icon, 意思是  Show in new window, 按下後, 會開 browser 的新視窗
3. 自行到 browser 下, 輸入網址  http://localhost:4321 (實際位址可能會有變動, 需查看 RStudio 視窗內容顯示的網址, 類似如下的內容)

```
― Creating your new site
| Installing the theme yihui/hugo-lithium from github.com
trying URL 'https://github.com/yihui/hugo-lithium/archive/master.tar.gz'
Content type 'application/x-gzip' length unknown
downloaded 109 KB

| Adding the sample post to content/post/2020-12-01-r-rmarkdown/index.Rmd
| Converting all metadata to the YAML format
| Adding netlify.toml in case you want to deploy the site to Netlify
| Adding .Rprofile to set options() for blogdown
― The new site is ready
○ To start a local preview: use blogdown::serve_site(), or the RStudio add-in "Serve Site"
○ To stop a local preview: use blogdown::stop_server(), or restart your R session
> Want to serve and preview the site now? (y/n) y
Launching the server via the command:
  C:/Users/mjiang/AppData/Roaming/Hugo/0.81.0/hugo.exe server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-lithium -D -F --navigateToChanged
Serving the directory . at http://localhost:4321
Launched the hugo server in the background (process ID: 32508). To stop it, call blogdown::stop_server() or restart the R session.
Rendering content/post/2020-12-01-r-rmarkdown/index.Rmd... Done.
```

網頁到此已順利創建完成, 接下來就是網頁內容的修改, 及如何 deploy 到 github.io