# 將 RMarkdown blogdown 內容 deploy 到 Netlify
參考 [Ref. 1 Using github  章節](https://alison.rbind.io/post/new-year-new-blogdown/#using-github)

## 設定 .gitignore : 雖然不知道這時候設定 .gitignore 的必要性, 還是照著說明做
```
file.edit(".gitignore")
```
RStudio 會將 cursor 移到左上角的檔案內容檢視視窗, 在該視窗類加上以下內容

```
## 原始內容 
.Rproj.user
.Rhistory
.RData
.Ruserdata
## 增加以下內容
.DS_Store
Thumbs.db
```

## blogdown  檢查 check_gitignore()  
執行第一次 commit 之前, 先用 blogdown 檢查 

```
> blogdown::check_gitignore()
```
不太清楚 [TODO] 再這裡的意義, 待研究
```
― Checking .gitignore
| Checking for items to remove...
○ Nothing to see here - found no items to remove.
| Checking for items to change...
○ Nothing to see here - found no items to change.
| Checking for items you can safely ignore...
○ Found! You have safely ignored: .DS_Store, Thumbs.db
| Checking for items to ignore if you build the site on Netlify...
● [TODO] When Netlify builds your site, you can safely add to .gitignore: /public/, /resources/
| Checking for files required by blogdown but not committed...
● [TODO] Found 1 file that should be committed in GIT:

  layouts/shortcodes/blogdown/postref.html
― Check complete: .gitignore
```

## blogdown 檢查  check_content()    

還不清楚這動作的意義, 待確認
```
> blogdown::check_content()
```
執行結果

```
― Checking content files
| Checking for validity of YAML metadata in posts...
○ All YAML metadata appears to be syntactically valid.
| Checking for previewed content that will not be published...
○ Found 0 files with future publish dates.
○ Found 0 files marked as drafts.
| Checking your R Markdown content...
○ All R Markdown files have been knitted.
○ All R Markdown output files are up to date with their source files.
| Checking for .html/.md files to clean up...
○ Found 0 duplicate .html output files.
○ Found 0 incompatible .html files to clean up.
| Checking for the unnecessary 'content/' directory in theme...
○ Great! Your theme does not contain the content/ directory.
― Check complete: Content

```

## 在 Netlify 網站上建置並且 Publish site    

參考 [Ref 1. Publish site  章節](https://alison.rbind.io/post/new-year-new-blogdown/#step-5-publish-site)

我們在這章節會使用比較高端的做法, 讓 Netlify 來將我們建立的網站, 建置到 github 上. 
1. 到 [Netlify](https://www.netlify.com/) 網站
2. 用 github 的帳號去 sign up (無須建立新帳號)
3. log in 後, 選擇 New site from Git > Continuous Deployment: GitHub.
4. (optional) 到 (Netlify) menu 右上角 Site Setting 點選後, 更改 Change site name 到自己已歡的名字, 我挑選的是 marconijiang, 所以我的網站就是 https://marconijiang.netlify.app. 如果修改, 會是 Netlify 自行設定的網址名稱, 位於左上角類似 xxxx-yyyyy-zzzz.netlify.app 的網址 
5. 可以另開一個 browser 頁面, 輸入網址 marconijiang.netlify.app, 就可以看到自己的 github 上的內容 (這時候的內容是 github 網站的內容, 如果還沒跟電腦上的同步, 內容可能是空的)


## git 指令將電腦的內容更新於 github
移到 RStudio 左下角的 terminal (console 右邊), 透過一般的 git  指令去更新  github 上的內容 

```
## 這時候, 目錄位址應該是從網頁內容 git clone 下來的目錄, 都是 xxxx.github.io
## 像我的目錄就是 marconijiang.github.io 
$ git add *
$ git commit -m "init commit"
$ git push origin main      # 最近, github 將 "master" branch 改成 main
##  需要輸入 github 的 user id 跟 password
```

這時候, 再回到 browser 的 https://marconijiang.netlify.app 稍稍等個一分鐘, 網頁會自動更新到最新的內容