`r if (knitr::is_html_output()) '
# References 參考文獻  {-}
'`

```{r, echo=FALSE}
referencescounter <- 0
```

本文蒐集所有 TinyML 官網相關的訊息

TinyML 出版書籍  
`r referencescounter<-referencescounter+1; referencescounter`. 英文版 [TinyML by Pete Warden, Daniel Situnayake](https://www.oreilly.com/library/view/tinyml/9781492052036/)  
`r referencescounter<-referencescounter+1; referencescounter`. 中文版 [TinyML TensorFLow Lite 機器學習中文版](https://www.books.com.tw/products/0010865580)    


TinyML events and activities  
`r referencescounter<-referencescounter+1; referencescounter`. [TinyML summit organization](https://www.tinymlsummit.org)  
`r referencescounter<-referencescounter+1; referencescounter`. [TinyML summit 2021](https://events.eventee.co/detail/tinyml-summit-2021-7883)  
`r referencescounter<-referencescounter+1; referencescounter`. [Tiny summit 2021 Youtube playback - partial only](https://www.youtube.com/channel/UC9iWqvsWjhowkHWVJquHwkg)  
`r referencescounter<-referencescounter+1; referencescounter`. [Meet up - 舊金山灣區](https://www.meetup.com/tinyML-Enabling-ultra-low-Power-ML-at-the-Edge/)  
`r referencescounter<-referencescounter+1; referencescounter`. [Meet up - 德州奧斯汀](https://www.meetup.com/meetup-group-NoKBhhJK/)    
`r referencescounter<-referencescounter+1; referencescounter`. [SIG Micro - TensorFlow Embedded Group](https://github.com/tensorflow/community/blob/master/sigs/micro/CHARTER.md)  
`r referencescounter<-referencescounter+1; referencescounter`. [SIG Micro mailing list](https://groups.google.com/a/tensorflow.org/forum/#!forum/micro)  
`r referencescounter<-referencescounter+1; referencescounter`. [SIG Micro Gitter chat channel](https://gitter.im/tensorflow/sig-micro)  
`r referencescounter<-referencescounter+1; referencescounter`. [SIG Micro monthly meeting notes and agenda](https://goo.gle/tf-micro-notes)  
  
TensorFlow Lite Micro  
`r referencescounter<-referencescounter+1; referencescounter`. [Tensorflow.org 官網](https://www.tensorflow.org/lite/guide)  
`r referencescounter<-referencescounter+1; referencescounter`. [TensorFlow for microcontroller - 官網](https://www.tensorflow.org/lite/microcontrollers)  
`r referencescounter<-referencescounter+1; referencescounter`. [TensorFlow for Micro Github 官網 open source 原始程式](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro)  

TensorFlow Lite Micro 應用  
`r referencescounter<-referencescounter+1; referencescounter`. [Tensorflow Lite Micro on ESP32](https://blog.tensorflow.org/2020/08/announcing-tensorflow-lite-micro-esp32.html)  
`r referencescounter<-referencescounter+1; referencescounter`. [ARM - build voice assistant on Cortex-M  with TFLM](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/build-arm-cortex-m-voice-assistant-with-google-tensorflow-lite)  

Pete Warden 及相關資料  
`r referencescounter<-referencescounter+1; referencescounter`. [Pete Warden's blog](https://petewarden.com/?s=tinyml&submit=Search)  
`r referencescounter<-referencescounter+1; referencescounter`. [Paper - TensorFlow Lite Micro](https://arxiv.org/pdf/2010.08678.pdf)  
`r referencescounter<-referencescounter+1; referencescounter`. [Pete youtube TinyML book #1 chap 4 - hello world training model](https://www.youtube.com/watch?v=8N6-WQsxwxA)  
`r referencescounter<-referencescounter+1; referencescounter`. [Pete youtube TinyML book #2 chap 5/6 - Deploying the Hello World model on an Arduino](https://www.youtube.com/watch?v=AfAyHheBk6Y)  
`r referencescounter<-referencescounter+1; referencescounter`. [Pete youtube TinyML book #3 - Introduction to TensorFlow Lite for Microcontrollers](https://www.youtube.com/watch?v=_NcG5estXOU)  
`r referencescounter<-referencescounter+1; referencescounter`. [Pete youtube TinyML book #4 - Quantization](https://www.youtube.com/watch?v=-jBmqY_aFwE)  
`r referencescounter<-referencescounter+1; referencescounter`. [Pete youtube What's TinyML good for \@ AIoT Dev Summit keynote](https://www.youtube.com/watch?v=Wuq2aP5O5Z0)  
`r referencescounter<-referencescounter+1; referencescounter`. [Getting Started with TinyML - Pete Warden - TinyML.org - March 31, 2020](https://forums.tinyml.org/t/getting-started-with-tinyml-pete-warden-march-31-2020/22)  
`r referencescounter<-referencescounter+1; referencescounter`. [Getting Started with TinyML - Pete Warden - TinyML.org - March 31, 2020 - youtube](https://www.youtube.com/watch?v=soOM1F70Boc)  
`r referencescounter<-referencescounter+1; referencescounter`. [Getting Started with TinyML - Pete Warden - TinyML.org - March 31, 2020 - slides](https://cms.tinyml.org/wp-content/uploads/talks2020/tinyML_Talks_200331_Pete_Warden.pdf)  
`r referencescounter<-referencescounter+1; referencescounter`. [Pete Warden, Staff Research Engineer and TensorFlow Lite development lead at Google, presents the "Using TensorFlow Lite to Deploy Deep Learning on Cortex-M Microcontrollers" tutorial at the May 2019 Embedded Vision Summit](https://www.edge-ai-vision.com/2019/06/using-tensorflow-lite-to-deploy-deep-learning-on-cortex-m-microcontrollers-a-presentation-from-google/)  
`r referencescounter<-referencescounter+1; referencescounter`. [Introducing the SparkFun Edge - Tiny models on tiny computers!](https://www.hackster.io/news/introducing-the-sparkfun-edge-34c9eb80a000)  


關於 TinyML 的另一位作者, 已經離開 Google 的 Daniel Situnayake 及他目前工作的公司 Edge Impluse   
`r referencescounter<-referencescounter+1; referencescounter`. [Daniel Situnayake's blog](https://situnayake.com)  
`r referencescounter<-referencescounter+1; referencescounter`. [Edge Impluse](https://docs.edgeimpulse.com/docs/getting-started?fbclid=IwAR10Gtry8NInWcRQfpV1SXSxefwdhUyHbxEJOUe8JsiJGQpR7ecYeTcjW5Y)

TensorFlow Lite Micro benchmark : 厲害的 stupid projects, 在不同的 embedded controller 做 TFLM 的 benchmark  
`r referencescounter<-referencescounter+1; referencescounter`. [Stupid projects - Machine Learning on Embedded (Part 1)](https://www.stupid-projects.com/machine-learning-on-embedded-part-1/)  
`r referencescounter<-referencescounter+1; referencescounter`. [Tensorflow 2.1.0 for microcontrollers benchmarks on STM32F746](https://www.stupid-projects.com/tensorflow-2-1-0-for-microcontrollers-benchmarks-on-stm32f746/)  

其它框架  
`r referencescounter<-referencescounter+1; referencescounter`. [uTensor - by ARM Neil Tan](https://github.com/uTensor/uTensor)  
`r referencescounter<-referencescounter+1; referencescounter`. [Microsoft - Embedded Learning Library (ELL)](https://microsoft.github.io/ELL/) : 主要針對 Arduino 與 micro:bit 平台  
`r referencescounter<-referencescounter+1; referencescounter`. [Neural Network on Mobile (nnom) by Ma Jianjia - github](https://github.com/majianjia/nnom)  

其它  

